on:
  push:
    branches: master
  schedule:
  - cron: '0 16 * * *'
name: Link checker
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Link Checker
        uses: peter-evans/link-checker@v1.2.2      
        with:
          args: -v -r *
